const PDFDocument = require('pdfkit');

exports.generatePDF = async (estimate) => {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      const pdfData = Buffer.concat(buffers);
      resolve(pdfData);
    });

    // Header
    doc.fontSize(25)
       .font('Helvetica-Bold')
       .text('Project Cost Estimator', 50, 50)
       .fontSize(12)
       .font('Helvetica')
       .text(`Estimate #: ${estimate.estimateNumber}`, 50, 100)
       .text(`Date: ${new Date(estimate.createdAt).toLocaleDateString()}`, 50, 115)
       .text(`Status: ${estimate.status}`, 50, 130);

    // Project Information
    doc.fontSize(16)
       .font('Helvetica-Bold')
       .text('Project Information', 50, 180)
       .moveDown();

    doc.fontSize(12)
       .font('Helvetica')
       .text(`Project Name: ${estimate.project.name}`, 50, 210)
       .text(`Project Type: ${estimate.project.projectType}`, 50, 225)
       .text(`Duration: ${estimate.project.duration} months`, 50, 240)
       .text(`Team Size: ${estimate.project.teamSize} people`, 50, 255)
       .text(`Complexity: ${estimate.project.complexityLevel}`, 50, 270);

    // Cost Breakdown
    doc.fontSize(16)
       .font('Helvetica-Bold')
       .text('Cost Breakdown', 50, 320)
       .moveDown();

    const y = 360;
    doc.fontSize(12)
       .font('Helvetica')
       .text('Labor Cost:', 50, y)
       .text(`$${estimate.costBreakdown.laborCost.toLocaleString()}`, 300, y, { align: 'right' })
       
       .text('Material Cost:', 50, y + 20)
       .text(`$${estimate.costBreakdown.materialCost.toLocaleString()}`, 300, y + 20, { align: 'right' })
       
       .text('Equipment Cost:', 50, y + 40)
       .text(`$${estimate.costBreakdown.equipmentCost.toLocaleString()}`, 300, y + 40, { align: 'right' })
       
       .text('Miscellaneous Cost:', 50, y + 60)
       .text(`$${estimate.costBreakdown.miscCost.toLocaleString()}`, 300, y + 60, { align: 'right' });

    // Total
    doc.moveTo(50, y + 90)
       .lineTo(550, y + 90)
       .stroke();

    doc.fontSize(14)
       .font('Helvetica-Bold')
       .text('Total Estimated Cost:', 50, y + 110)
       .text(`$${estimate.costBreakdown.totalCost.toLocaleString()}`, 300, y + 110, { align: 'right' });

    // Notes
    if (estimate.notes) {
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text('Notes', 50, 550)
         .moveDown();

      doc.fontSize(12)
         .font('Helvetica')
         .text(estimate.notes, 50, 580);
    }

    // Footer
    doc.fontSize(10)
       .font('Helvetica')
       .text(
         'Generated by Project Cost Estimator',
         50,
         doc.page.height - 50,
         { align: 'center' }
       );

    doc.end();
  });
};